version: "3.9"
services:
  personalinfo-spa-client:
    container_name: personalinfo-spa-client
    stdin_open: true
    tty: true
    build:
      context: ./PersonalInfo.Spa.PersonalInfo
      dockerfile: Dockerfile.local
    ports:
      - "7001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
  personalinfo-api-newsfeed:
    container_name: personalinfo-api-newsfeed
    build:
      context: ./PersonalInfo.Api.NewsFeeds
      dockerfile: Dockerfile.local
    ports:
      - "6001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
  personalinfo-api-weather:
    container_name: personalinfo-api-weather
    build:
      context: ./PersonalInfo.Api.Weather
      dockerfile: Dockerfile.local
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080